import { StyleSheet } from 'react-native';
export const colors = {
  bg: '#0D0D0D',
  surface: '#151515',
  raised: '#1B1B1B',
  border: '#28282C',
  text: '#F1F1F3',
  muted: '#A1A1AA',
  blue: '#365FFF',
  light: '#8DA3FF',
  green: '#80D5AA',
  red: '#FF929A',
};
export const fonts = {
  regular: 'DMSans_400Regular',
  medium: 'DMSans_500Medium',
  bold: 'DMSans_700Bold',
  heading: 'BarlowCondensed_700Bold',
};
export const s = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  content: {
    padding: 22,
    paddingBottom: 32,
    gap: 24,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  stack: { gap: 12 },
  grow: { flex: 1 },
  eyebrow: {
    fontFamily: fonts.bold,
    fontSize: 10,
    letterSpacing: 2.2,
    color: colors.light,
    textTransform: 'uppercase',
  },
  heading: {
    fontFamily: fonts.heading,
    fontSize: 38,
    lineHeight: 40,
    color: colors.text,
    textTransform: 'uppercase',
  },
  title: { fontFamily: fonts.bold, fontSize: 17, color: colors.text },
  body: { fontFamily: fonts.regular, fontSize: 14, lineHeight: 22, color: colors.muted },
  small: { fontFamily: fonts.medium, fontSize: 11, lineHeight: 17, color: colors.muted },
  label: { fontFamily: fonts.bold, fontSize: 13, color: colors.text },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 18,
    padding: 18,
    gap: 14,
  },
  button: {
    minHeight: 50,
    backgroundColor: colors.blue,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  buttonText: { fontFamily: fonts.bold, fontSize: 13, color: '#FFFFFF' },
  secondary: { backgroundColor: colors.raised, borderWidth: 1, borderColor: colors.border },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    minHeight: 44,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  chipActive: { borderColor: colors.blue, backgroundColor: '#18234D' },
  input: {
    backgroundColor: colors.raised,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    color: colors.text,
    padding: 16,
    fontFamily: fonts.regular,
    fontSize: 15,
    minHeight: 52,
  },
  divider: { height: 1, backgroundColor: colors.border },
  note: { color: colors.light, fontFamily: fonts.regular, fontSize: 12, lineHeight: 19 },
  error: { color: colors.red, fontFamily: fonts.medium, fontSize: 13, lineHeight: 20 },
  badge: {
    backgroundColor: '#18234D',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
});
